### ISSUE TITLE
Use the latest available API versions

### ISSUE THREAD

**Issue by slokhorst** [DivideBV/Postnl#24]
We don't use the latest available API interfaces from PostNL:
- [x] Confirming webservice: we use `1_7`, [latest is `1_9`](https://developer.postnl.nl/apis/confirming-webservice/documentation) (PR #25)
- [x] Labelling webservice: we use `1_8`, [latest is `2_0`](https://developer.postnl.nl/apis/labelling-webservice/documentation) (PR #27)
- [x] Location webservice: we use `2_0`, [latest is `2_1`](https://developer.postnl.nl/apis/location-webservice/documentation) (PR #30)

I think the changes are minor, but it is always good to use the latest available version.

**Comment by ameenross** [comment]
(copied from #25)

I've been thinking about a lazy way to handle this. I can't really be expected to monitor the API versions and constantly update the library. Perhaps it could somehow be automated to an extent, but in theory it really needs testing to know it still works.

I wonder why the API versions increase so often, especially when there doesn't appear to be a backward compatibility breaking change... it's a stupid release policy for an API I must say.

**Comment by slokhorst** [comment]
I don't see any other way. Each new version potentially requires manual intervention. (In this case, the Labelling and Location webservice require changes, the Confirming webservice doesn't)

Also, it isn't a big problem if we stick to old versions for a while, since all previous versions seem to be supported. If someone wants to take the time to make the required changes to switch to the new version, they can, but there is no reason to rush it or actively monitor new versions. I assume that if PostNL stops supporting an older version, they'll let us know.

**Comment by ameenross** [comment]
Fair enough. For completeness, I think we should also document the API versions used in the README.

**Comment by slokhorst** [comment]
I agree, see #26

**Comment by ameenross** [comment]
Created PR https://github.com/DivideBV/Postnl/pull/27 to update labelling service

**Comment by ameenross** [comment]
Created #30, location service
